#################################################################
###################### NexT Configuration #######################
#################################################################

# ============================================================= #
# ============= Theme Core Configuration Settings ============= #
# ============================================================= #

custom_file_path:
#   sidebar: source/_data/sidebar.njk
  footer: source/_data/footer.njk
#   variable: source/_data/variables.styl
#   style: source/_data/styles.styl

# ============================================================= #
# ====================== Scheme Settings ====================== #
# ============================================================= #

scheme: Gemini
darkmode: true

# ============================================================= #
# ================= Site Information Settings ================= #
# ============================================================= #

creative_commons:
  license: by-nc-sa
  sidebar: true
  post: true
  language: deed.zh

favicon:
  small: /images/favicon-16x16.png
  medium: /images/favicon-32x32.png
  apple_touch_icon: /images/apple-touch-icon.png
  safari_pinned_tab: /images/logo.svg
  android_manifest: /images/site.webmanifest
  ms_browserconfig: /images/browserconfig.xml


# ============================================================= #
# ======================= Menu Settings ======================= #
# ============================================================= #

menu:
  home: / || fa fa-bell
  archives: /archives/ || fa fa-archive
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-list-alt
  开源: /open-source/ || fab fa-github


menu_settings:
  icons: true
  badges: true

# ============================================================= #
# ===================== Sidebar Settings ====================== #
# ============================================================= #

sidebar:
  position: left
  display: post
  padding: 18
  offset: 12

avatar:
  url: /images/logo.jpg
  rounded: true

social:
  GitHub: https://github.com/wangyonghong || fab fa-github
  Twitter: https://twitter.com/yonghong365 || fab fa-twitter
  FB Page: https://www.facebook.com/yonghong365 || fab fa-facebook
  Weibo: https://weibo.com/0xl2oot || fab fa-weibo
  E-Mail: mailto:yonghongwang@163.com || fa fa-envelope
  RSS: /atom.xml || fa fa-rss
  Gitter: https://gitter.im/wangyonghong || fab fa-gitter

social_icons:
  enable: true
  icons_only: true
  transition: true

toc:
  enable: true
  number: true
  wrap: true

# ============================================================= #
# ====================== Footer Settings ====================== #
# ============================================================= #

footer:
  since: 2020
  icon:
    name: fa fa-heart
    animated: true
    # color: "#808080"
  copyright: yonghong
  powered: false
  beian:
    enable: true
    icp: 京ICP备 18012168号-5

busuanzi_count:
  enable: true


# ============================================================= #
# ======================= Post Settings ======================= #
# ============================================================= #

post_meta:
  item_text: true
  created_at: true
  updated_at:
    enable: true
    another_day: true
  categories: true


symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
  separated_meta: true
  item_text_total: true

reward_settings:
  # If true, a donate button will be displayed in every article by default.
  enable: true
  animation: false
  comment: Buy me a coffee

reward:
  wechatpay: /images/wechatpay.jpg
  alipay: /images/alipay.jpg
  paypal: /images/paypal.png

follow_me:
  Twitter: https://twitter.com/yonghong365 || fab fa-twitter
  #WeChat: /images/wechat_channel.jpg || fab fa-weixin
  RSS: /atom.xml || fa fa-rss

# ============================================================= #
# ==================== Misc Theme Settings ==================== #
# ============================================================= #

mobile_layout_economy: true

codeblock:
  theme:
    light: default
    dark: tomorrow-night
  copy_button:
    enable: true
    style: default

back2top:
  enable: true
  sidebar: false
  scrollpercent: true

github_banner:
  enable: true
  permalink: https://github.com/wangyonghong/yonghong-me
  title: yonghong-me


# ============================================================= #
# ======================= SEO Settings ======================== #
# ============================================================= #

disable_baidu_transformation: true

index_with_subtitle: true

exturl: true

google_site_verification: OnjTLbjHCNhb2DmVFSKHIiIT7K6UOcNW4INMAr5XVrg
yandex_site_verification: bb13e36c670d98c2
baidu_site_verification: code-mDlCdb61pU
baidu_push: true

# ============================================================= #
# =============== Third Party Services Settings =============== #
# ============================================================= #

math:
  mathjax:
    enable: true

pjax: true
fancybox: true
mediumzoom: true
pangu: true

quicklink:
  enable: true
  home: true
  archive: true
  delay: true
  timeout: 3000
  priority: true




# ============================================================= #
# =================== Comments and Widgets ==================== #
# ============================================================= #

comments:
  lazyload: true

livere_uid: MTAyMC81MTYxMi8yODA5Mw==

rating:
  enable: true
  id:     27385
  color:  "#fc6423"

add_this_id: ra-5f6aa34fc43297b3


# ============================================================= #
# ================= Statistics and Analytics ================== #
# ============================================================= #

# google_analytics:
#   tracking_id: 


# ============================================================= #
# ====================== Search Services ====================== #
# ============================================================= #

local_search:
  enable: true
  trigger: auto
  top_n_per_article: 1


# ============================================================= #
# ======================== Tag Plugins ======================== #
# ============================================================= #

note:
  style: simple
  icons: true
  light_bg_offset: -3

tabs:
  transition:
    tabs: true
    labels: true

mermaid:
  enable: true


# ============================================================= #
# ==================== External Libraries ===================== #
# ============================================================= #

motion:
  async: true

vendors:
  internal: jsdelivr
