#################################################################
###################### NexT Configuration #######################
#################################################################

# ============================================================= #
# ============= Theme Core Configuration Settings ============= #
# ============================================================= #

custom_file_path:
  head: source/_data/head.njk
  postMeta: source/_data/post-meta.njk
  footer: source/_data/footer.njk
  bodyEnd: source/_data/body-end.njk
  variable: source/_data/variables.styl
#   style: source/_data/styles.styl

# ============================================================= #
# ====================== Scheme Settings ====================== #
# ============================================================= #

scheme: Gemini
darkmode: true

# ============================================================= #
# ================= Site Information Settings ================= #
# ============================================================= #

creative_commons:
  license: by-nc-sa
  sidebar: true
  post: true
  language: deed.zh

favicon:
  small: /images/favicon-16x16.png
  medium: /images/favicon-32x32.png
  apple_touch_icon: /images/apple-touch-icon.png
  safari_pinned_tab: /images/logo.svg
  android_manifest: /images/site.webmanifest
  ms_browserconfig: /images/browserconfig.xml


# ============================================================= #
# ======================= Menu Settings ======================= #
# ============================================================= #

menu:
  home: / || fa fa-bell
  archives: /archives/ || fa fa-archive
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-list-alt
  开源: /open-source/ || fab fa-github


menu_settings:
  icons: true
  badges: true

# ============================================================= #
# ===================== Sidebar Settings ====================== #
# ============================================================= #

sidebar:
  position: left
  width: 360
  display: post
  padding: 18
  offset: 12

avatar:
  url: /images/logo.jpg
  rounded: true

social:
  GitHub: https://github.com/wangyonghong || fab fa-github
  E-Mail: mailto:yonghongwang@163.com || fa fa-envelope
  RSS: /atom.xml || fa fa-rss
  Gitter: https://gitter.im/wangyonghong || fab fa-gitter

social_icons:
  enable: true
  icons_only: true
  transition: true

toc:
  enable: true
  number: true
  wrap: true

# ============================================================= #
# ====================== Footer Settings ====================== #
# ============================================================= #

footer:
  since: 2020
  icon:
    name: fa fa-heart
    animated: true
    # color: "#808080"
  copyright: yonghong
  powered: false
  beian:
    enable: false
    icp: 京ICP备 18012168号-5

busuanzi_count:
  enable: true


# ============================================================= #
# ======================= Post Settings ======================= #
# ============================================================= #

post_meta:
  item_text: true
  created_at: true
  updated_at:
    enable: true
    another_day: true
  categories: true


symbols_count_time:
  symbols: true
  time: true
  total_symbols: true
  total_time: true
  separated_meta: true
  item_text_total: true

reward_settings:
  # If true, a donate button will be displayed in every article by default.
  enable: true
  animation: false
  comment: Buy me a coffee

reward:
  wechatpay: /images/wechatpay.jpg
  alipay: /images/alipay.jpg

follow_me:
  RSS: /atom.xml || fa fa-rss

# ============================================================= #
# ==================== Misc Theme Settings ==================== #
# ============================================================= #

mobile_layout_economy: true

codeblock:
  theme:
    light: default
    dark: tomorrow-night
  copy_button:
    enable: true
    style: default

back2top:
  enable: true
  sidebar: false
  scrollpercent: true

github_banner:
  enable: true
  permalink: https://github.com/wangyonghong/yonghong-me
  title: yonghong-me


# TagCloud settings for tags page.
tagcloud:
  min: 12 # Minimun font size in px
  max: 30 # Maxium font size in px
  amount: 9999 # Total amount of tags
  orderby: length # Order of tags
  order: -1 # Sort order


# ============================================================= #
# ======================= SEO Settings ======================== #
# ============================================================= #

index_with_subtitle: true

exturl: true

google_site_verification: OnjTLbjHCNhb2DmVFSKHIiIT7K6UOcNW4INMAr5XVrg

# ============================================================= #
# =============== Third Party Services Settings =============== #
# ============================================================= #

math:
  mathjax:
    enable: true

pjax: false
fancybox: true
mediumzoom: true
pangu: true

quicklink:
  enable: true
  home: true
  archive: true
  delay: true
  timeout: 3000
  priority: true




# ============================================================= #
# =================== Comments and Widgets ==================== #
# ============================================================= #

comments:
  style: tabs
  active: disqus
  storage: true
  lazyload: true

livere_uid: MTAyMC81MTYxMi8yODA5Mw==

# Gitalk
# Demo: https://gitalk.github.io
gitalk:
  enable: true
  github_id: wangyonghong # Github repo owner
  repo: gitalk # Repository name to store issues
  client_id: 0e42a09d2799751b9ba7 # Github Application Client ID
  client_secret: 3e04e5109cf9e3cc34d68deb668842c9c5139846 # Github Application Client Secret
  admin_user: wangyonghong # GitHub repo owner and collaborators, only these guys can initialize github issues
  distraction_free_mode: true # Facebook-like distraction free mode
  # Gitalk's display language depends on user's browser or system environment
  # If you want everyone visiting your site to see a uniform language, you can set a force language value
  # Available value: en, es-ES, fr, ru, zh-CN, zh-TW
  # language:

disqus:
  enable: true
  shortname: yonghong-tech
  count: false


# ============================================================= #
# ================= Statistics and Analytics ================== #
# ============================================================= #

# google_analytics:
#   tracking_id: 


# ============================================================= #
# ====================== Search Services ====================== #
# ============================================================= #

local_search:
  enable: true
  trigger: auto
  top_n_per_article: 1


# ============================================================= #
# ======================== Tag Plugins ======================== #
# ============================================================= #

note:
  style: simple
  icons: true
  light_bg_offset: -3

tabs:
  transition:
    tabs: true
    labels: true

mermaid:
  enable: true


# ============================================================= #
# ==================== External Libraries ===================== #
# ============================================================= #

motion:
  enable: false

vendors:
  internal: jsdelivr
  # 强制指定最新版本
  gitalk_js: https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.min.js
  gitalk_css: https://cdn.jsdelivr.net/npm/gitalk@1/dist/gitalk.css